### ISSUE TITLE
Criar o botão 'Enviar sugestão'.

### ISSUE THREAD

**Issue by EvertonMelo** [esdrasedu/ethereum_sp_dao#11]
Para facilitar o uso criar o botao ( ENVIAR SUGESTAO) 
a ideia é automatizar o a criação de novas **issues**

**Comment by EvertonMelo** [comment]
add [Enviar](https://github.com/esdrasedu/ethereum_sp_dao/pull/12)

**Comment by esdrasedu** [comment]
done in #12
